# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca6eb06a82b45ef1328ff07793b7c6d7f480362595989b51836fa0d7f1b97df09f429c7f234063cd2923137ea3bbc29aa8f5ee716525e31ff01f9e0d65953fb4

test:
  secret_key_base: c9811ea02da040eca1c216a665d16a14c174df1297323e1d3ce2fbf3c27526e48203ff4099fc290848dc3d24f7f213d4946bebdabf1d6bb0c27af271e8018c05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
