# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f077b93a56c869237f2f0383b035e41dc3742d70b0cd64cb50f48e85b5a837def693a7f2af50d39a63b63ae3b733d4be0f15cde32fbec2cf4a564316bf2feee9

test:
  secret_key_base: 5201a75bb29b63cd958f4f7967fe1791b092508a90ec982e72765ce09d738b83ae4643edda63651da00191806e1b51d27cd4599522ab120e520d8cdae8c34d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
